-- ===== TODOS OS PRODUTOS (DEDUPLICADOS) =====
INSERT INTO public.products (name, group_id) VALUES 
('Açúcar Morena', 9),
('Mandioquinha Verde', 10),
('Pão de Quinoa Quente', 17),
('Alface Cilantro Fresh', 9),
('Açúcar Branqueado', 9),
('Molho de Chilli', 20),
('Farofa Branca', 4),
('Cebola Roçada', 1),
('Sorva de Laranja', 17),
('Cebola Vermelha Red Onion', 10),
('Pão de Queijo Quente', 20),
('Manteiga Salgada', 10),
('Shampoo para Cozinha', 20),
('Tapioca Amarela', 18),
('Mandioca Amarela Moqueada', 10),
('Frutas Azuis Conservadas', 15),
('Tomilho Fresco', 20),
('Massa de Pão Instantânea', 8),
('Alho Crispas', 10),
('Ovos Brancos', 8),
('Farinha de Mandioca Amarela', 8),
('Papel Toalha', 10),
('Peixe Gordo Assado', 4),
('Molho de Cogumelos Classic', 20),
('Cogumelo Shiitake Fresh', 20),
('Aipo Seco', 8),
('Pimenta Vermelha Pó', 4),
('Noz Pretas', 10),
('Farofa Tostada', 10),
('Arroz Doce para Creme', 6),
('Salsicha Carioca Grelhada', 19),
('Tortilha de Fubá com Ovo', 4),
('Cebola Roja', 1),
('Farofa Rizada', 10),
('Coxinha Grelada com Salsa', 5),
('Sorvete de Morango Natural', 4),
('Bananito Amarelo', 9),
('Bife Churrasco', 10),
('Creme de Leite Condensado', 7),
('Bananito Amarelo Maduro', 9),
('Açúcar Granulada 250g', 9),
('Cebola Enxofre em Cabeças', 17),
('Couve Flor', 17),
('Chouriço Caloroso Spicy Chourico', 9),
('Pão Franco', 10),
('Noz Casca Integral', 11),
('Farofa Tostada sem Salsa', 8),
('Feijão Preto Embarcado Gourmet', 4),
('Fiosco Seco', 5),
('Cebola Ralada Fresh', 20),
('Fiosco Fresco', 5),
('Tofu Seco', 10),
('Mandioca Preta 1,5kg', 10),
('Farofa Fina', 4),
('Feijão Preto Embarcado', 8),
('Mandioca Grelhada', 10),
('Ovos de Codorniz Fresh', 8),
('Coxinha de Frango Fresca', 5),
('Pimenta Malagueta Seca', 1),
('Cebola Rija', 1),
('Cebola Amarela Cabeças', 1),
('Xarope de Açaí Natural', 9),
('Pão de Queijo Fresco', 20),
('Molho de Ostras Tradicional', 17),
('Azeite Extra Virgin Olive Oil', 11),
('Cebola Caramelizada', 10),
('Coxo de Cordeiro Refogado', 17),
('Mostarda American Style Mustard', 20),
('Chicória Ralada Fresh', 20),
('Molho de Azeite Tradicional', 20),
('Leite descremado', 7),
('Salsicha Calabresa', 13),
('Cebolla Roja Fina', 17),
('Fio Dental Duplo', 3),
('Bacon Gordo Raspado', 4),
('Noz Canada Em Grãos', 17),
('Salsicha Calorosa', 8),
('Molho de Barbecue 250g', 20),
('Sal Grosso Coarse', 8),
('Cebola Crispiante', 1),
('Sorvete de Banana Natural', 6),
('Açaí Branco Congelado', 18),
('Mamão Pulpado Fino', 17),
('Carne Moída para Burgers', 6),
('Coxo de Frango Refogado', 17),
('Mamão Pulpado Conserve', 11),
('Açúcar Granulado 1kg', 9),
('Molho de Pimenta Calabresa', 20),
('Coxo De Frango Em Filés', 17),
('Pão De Milho Integral 5kg', 11),
('Fio Dental', 3),
('Aipo Fresco', 4),
('Mamão Manteiga', 10),
('Frijoles Negros Tipo 3', 3),
('Ketchup Condimento', 20),
('Açucar Granulado', 9);

INSERT INTO public.products (name, group_id) VALUES 
('Peixe Gordo Fresco', 4),
('Azeitona Escalvada Em Tiras', 19),
('Ketchup Classic 200ml', 20),
('Alface Americana Fresh', 9),
('Açaí Amarelo Fresh', 9),
('Mamão Maduro Fino', 17),
('Papel Toalha Higiênico', 8),
('Pimenta Coração de Jesus', 17),
('Abacate Verde Fresh', 20),
('Melão Semeador', 17),
('Paprika Fina', 10),
('Tomilho Fresco Fresh Thyme', 20),
('Arroz Parboiled Instantâneo', 17),
('Pimenta-do-Reino Cravada', 8),
('Açúcar Irmãos 1kg', 9),
('Molho de Tomate Cremoso', 20),
('Coxo de Galinha Refogado', 3),
('Farofa Integral 2kg', 11),
('Salsicha de Carne Mista Refrescada', 6),
('Goiaba Vermelha Fresh', 4),
('Rizinho Preto Congelado', 18),
('Tortilha Integral', 11),
('Chouriço Italiano', 8),
('Cogumelo Shiitake', 8),
('Mandioca Amarela Frita', 15),
('Goma Elástica', 4),
('Salsa de Laranja Natural', 17),
('Coxo De Pato Em Filés', 5),
('Ovo Cru', 8),
('Feijão Preto Manteiga', 18),
('Manteiga Salgada Refrescada', 10),
('Farofa Instantânea', 10),
('Geléia de Pessego', 5),
('Batata Doce Ralada', 4),
('Coxão Mole Resfriado Shredded', 2),
('Rapadura Brown Sugar', 10),
('Batata Doce Assada', 8),
('Pimenta Verde Crispas', 4),
('Coxão Grelhado em Bocados', 17),
('Picanha de Porco Pork Shoulder Blade', 20),
('Molho de Chocoladeiro Tradicional', 17),
('Picles Brancos Em Rodinho', 17),
('Ovos Brancos Duzinhos', 8),
('Frutas Congeladas Mix', 15),
('Farofa Preto', 4),
('Margarina Solúvel 250g', 5),
('Pimenta Calabresa Fina', 5),
('Papel Higiênico Duplo', 8),
('Aceite de Girassol Extra Virgin', 9),
('Salsa Cruda Picante', 5),
('Mandioca Preta Frita', 15),
('Xarope de Morango Natural', 13),
('Sour Cream 1L', 13),
('Mostarda Gostosa 150g', 4),
('Arroz Integral Instantâneo', 11),
('Gelatinoso Desidratado', 2),
('Farinha de Rosca 1kg', 5),
('Arroz Branco Congelado', 18),
('Aipo Cru', 5),
('Couve-Flor Amarilla Integral', 11),
('Arroz Integral Whole Wheat Flour', 11),
('Pão Francês Crispado', 17),
('Pimenta Preta Molhada', 12),
('Arroz integral 2kg', 11),
('Farofa Gostosa', 4),
('Creme Fresh 750ml', 11),
('Arroz Doce com Canela', 17),
('Açúcar Demerara 500g', 9),
('Alface Americana Hidropônica', 9),
('Tapioca Pearl', 10),
('Queijo Ralado Shredded', 20),
('Mamão Seco', 18),
('Frijoles Rojos Tipo 2', 3),
('Molho de Tomate Picado', 20),
('Tomate Cereja Hidropônica', 1),
('Tomate Maduro', 10),
('Manteiga Patê', 14),
('Pimenta Serrana Granel', 14),
('Cebola Picada Moinhos', 1),
('Pimenta-do-Reino Molhada', 8),
('Gergelim Integral', 11),
('Molho de Soja Tamari', 20),
('Açaí Composto', 9),
('Molho de Soja Soy Sauce', 20),
('Chouriço Mexicano', 17),
('Açúcar Rapadura', 9),
('Creme Fresh 500ml', 11),
('Pessego Seco', 8),
('Ketchup Orgânico 250ml', 20),
('Ovo Pasteurizado', 8),
('Chouriço Gostoso', 4),
('Mamona Extrafina', 10),
('Biscoito Integral Crocante', 11),
('Coxão Mole Grelhado', 17),
('Pão Francês Instantâneo', 8),
('Açúcar Granulada 1kg', 9),
('Noz Macadâmia em Grãos', 17),
('Mandioca Branca Frita', 5),
('Salsa de Tomate Culinada', 17),
('Mandioca Frita', 15);

INSERT INTO public.products (name, group_id) VALUES 
('Fubá Preto Tipo 1', 8),
('Hortelã Fresca', 5),
('Fubá Tortilha', 10),
('Pão Francês Inteiro', 17),
('Salsa de Açaí Natural', 9),
('Tomate Saborido em Conserva', 17),
('Hortelã Seca', 10),
('Salsicha Italiana Hot Dog', 1),
('Gelatinagem Frango', 6),
('Massa Torta Instantânea', 10),
('Coxão Mole Assado', 17),
('Cebola Roja Fresh', 20),
('Salsa de Tomate com Açafrão', 5),
('Salsa de Tomate Fresca', 5),
('Cebola Ralada Secca', 1),
('Bife de Fiosco Seco', 17),
('Alface Creste Hidropônica', 9),
('Risotto Pronto 1kg', 18),
('Biscoito com Avena', 5),
('Molho BBQ Tradicional', 20),
('Mandioca Preta 1.5kg', 11),
('Arroz Doce', 6),
('Aipo Seco Ralado', 4),
('Arroz Branco 5kg', 11),
('Couve Flor Ralado Congelado', 18),
('Linguiça Caseira Refrescada', 17),
('Ovo Ligeiramente Cru', 14),
('Roso de Frango Desfiado', 17),
('Leite Condensado 400ml', 7),
('Sorgo Amarelo Inteiro', 10),
('Pimenta-do-Reino Seca', 4),
('Molho de Tomate Orgânico', 20),
('Fiosco de Carne', 6),
('Tomates Cherri Hidropônicos', 9),
('Tapioca Instantânea', 10),
('Salsa Roja Picada', 8),
('Fraldinha para Salgados', 5),
('Arroz Branco Instantâneo 3kg', 4),
('Detergente Neutro', 8),
('Mel em Pó', 8),
('Cebola Crispada', 10),
('Hortelã Fresco Chopped', 12),
('Frango Comida Mole', 6),
('Café Solúvel 100g', 13),
('Café Instantâneo 100g', 13),
('Fava Preto', 5),
('Tofu Fresh', 11),
('Molho de Mostarda Clássico', 20),
('Aipo Curly', 11),
('Creme de Coco Natural', 12),
('Frango Desossado', 15),
('Salsa Verde 200ml', 9),
('Açúcar Moreno', 9),
('Melão Fresco', 12),
('Couve Tronchuda Ralado Fresh', 17),
('Açúcar Granulado', 9),
('Chouriço Gostoso Refrescado', 4),
('Coxo Mole Frito', 3),
('Coxo de Frango Mole Grelhado', 6),
('Roso de Carne Desfiado', 6),
('Coxo de Galinha Grelhado', 19),
('Cebola Amarilla Crispas', 10),
('Aipo Crispado', 17),
('Salsicha Casera Refrescada', 10),
('Fiosco de Carne Gourmet', 6),
('Peixe Grelado com Limão', 18),
('Risotto Instantâneo', 2),
('Pimenta Longa Green Fresh', 13),
('Favarela Preto', 5),
('Molho de Soja 250ml', 20),
('Pimenta Calabresa Em Grãos', 14),
('Azeitonas Escalvadas 300g', 10),
('Pimenta Malagueta Extra Grande', 15),
('Ovos de Codorniz', 8),
('Maçã Vermelha Enxertada', 17),
('Coxinha de Frango Congelado', 18),
('Molho de Cogumelos Italiano', 20),
('Cebola Roja Extra Grande', 1),
('Cebola Amarilla', 1),
('Pão Francês 12 unidades', 3),
('Coxinha Grelada sem Salsa', 5),
('Salsa Chili 300ml', 9),
('Ovomaltine Instantâneo', 8),
('Cebola Natural Picada', 1),
('Alface Americana Hidropônica Baby Leaf', 13),
('Picanha de Porco', 8),
('Churresco em Rodinho', 17),
('Torta de Limão', 17),
('Coxão Mole Refogado', 17),
('Salsa Cruda', 5),
('Xis da China', 11),
('Limão Siciliano Jarred', 17),
('Fio Dental Gelável', 5),
('Fio de Ovo 12 Unidades', 8),
('Molho de Tomate Tradicional', 20),
('Salsicha Casera', 8),
('Cebola Amarela Crispas', 10),
('Coxo de Frango Grelhado', 17),
('Frutas Secas Mix', 15),
('Hortelã Seco Dried Parsley', 2);

INSERT INTO public.products (name, group_id) VALUES 
('Salsa de Tomate Fina 200ml', 5),
('Feijão Preto Comida Mole', 8),
('Massa de Pão Italiano', 8),
('Chouriço Grelhado', 20),
('Salsa de Limão Natural', 9),
('Açúcar Pó', 9),
('Manteiga Softened', 11),
('Salsicha Italiana Fresca', 5),
('Picles Dourados em Tiras', 8),
('Papel Higiênico Extra Soft 2-Rolls', 12),
('Fubá Integral', 11),
('Tortas de Banana Fresh', 8),
('Mandioca Processada', 11),
('Mandioca Seca', 10),
('Massa de Pão Integral', 8),
('Arroz Branco Instantâneo', 9),
('Fiosco de Carne Premium', 6),
('Mussel Frozen 500g', 11),
('Pimenta Doce Sweet Pepper', 13),
('Açúcar Granulada', 9),
('Tomilho Fresco Chopped', 20),
('Feijão Preto Tipo 2', 18),
('Chapinha de Frango Gostoso', 4),
('Azeitona Preta Salgada', 10),
('Sorgo Amarelo Molido', 10),
('Acerola Seco 1kg', 9),
('Coxão de Frango Mole Resfriado', 3),
('Xarope de Laranja Natural', 6),
('Feijão Creme', 8),
('Noz Casca Pó', 14),
('Açúcar Demerara Light Brown Sugar', 9),
('Tomate Cereja Em Tiras', 17),
('Coxão Grelado Grilled Chicken Thighs', 20),
('Linguiça Fumada', 20),
('Pão de Pato Quente', 18),
('Açúcar Caramelo 1kg', 9),
('Salsa de Limão Orgânica', 9),
('Pimenta Verde Moledo', 8),
('Aipo Cru Ralado', 17),
('Crackers de Milho Salgados', 8),
('Cebolla Cruda', 1),
('Coxão Mole Grelhado Em Bocados', 17),
('Frutas Vermelhas Conservadas', 15),
('Creme de Manicure para Freguesia', 3),
('Açaí Amarelo Congelado', 18),
('Acerola Seco', 9),
('Fubá Moqueado', 20),
('Flocos de Arroz Instantâneo 2kg', 4),
('Creme de Leite 200ml', 7),
('Farofa com Azeite', 10),
('Farofa Branca White Rice Flour', 20),
('Arroz Integral 3kg', 11),
('Salsicha de Porco Fresca', 15),
('Açúcar Panela', 9),
('Mandioca Assada Ralada', 8),
('Couve-Flor Crispada', 10),
('Margarina Light 250g', 5),
('Mamão Fresh', 12),
('Hortelã Seco Ralado', 4),
('Azeite com Menta', 14),
('Coxo de Frango Assado', 17),
('Salsa de Abacate Natural', 9),
('Azeite Extra Virgin', 10),
('Pimenta Preto Black Pepper', 12),
('Café Turco Solúvel', 17),
('Algodão Branco Fino', 4),
('Frijoles Negros Tipo 2', 3),
('Cebola Vermelha', 1),
('Hortelã Congelada', 18),
('Molho De Soja Orgânico 250ml', 20),
('Couve-Flor Roja Integral', 17),
('Pimenta Desechada', 17),
('Cebola Rija Polpa', 1),
('Creme de Leite com Manteiga', 7),
('Couve Rizada', 10),
('Pão Francês 20 unidades', 5),
('Chicória Fresh', 20),
('Açafrão Pó', 8),
('Abacate Mago em Cabeças', 18),
('Sorvete Natural', 4),
('Aceite de Oliva Extra Virgin', 8),
('Salsa de Tomate Traditional Tomato Sauce', 1),
('Salsicha Grelada com Cebola', 1),
('Bife Encebollado', 17),
('Sour Cream Condimento', 20),
('Pão de Ló Instantâneo', 8),
('Abacate Amarelo Em Cabeças', 19),
('Leite Concentrado UHT', 7),
('Farofa Integral', 11),
('Salsa de Limão 250ml', 17),
('Farofa Integral Whole Wheat Flour', 11),
('Mandioca Amarela', 18),
('Picanha Moqueada', 20),
('Detergente Aromático', 20),
('Biscoito Integral com Sementes', 11),
('Mandioca Preta 2,5kg', 10),
('Risotto De Queijo Pronto 1kg', 18),
('Pão Italiano', 4),
('Açúcar Creme 1kg', 9),
('Café Preto Solúvel', 17);

INSERT INTO public.products (name, group_id) VALUES 
('Salsicha Chorizo Grelhada', 20),
('Azeitona Natural', 16),
('Mamão Verde Em Rodinho', 17),
('Salsa de Limão Lemon Sauce', 9),
('Fiosco de Frango', 3),
('Coxão Mole Resfriado', 2),
('Pimenta Bicolor Granel', 13),
('Chouriço Italiano Mince', 1),
('Pimenta Calabresa Fresh', 5),
('Molho de Azeite com Tomate', 20),
('Molho de Salsa Tradicional', 20),
('Coxo de Frango Salgado', 17),
('Spray para Pisos', 8),
('Molho de Azeite com Alho', 20),
('Mamão Amarelo em Tiras', 17),
('Tomate Cereja Fresco', 5),
('Tomate Cherry Fresco', 6),
('Mangas Carameladas', 12),
('Cebola Roja Rija', 17),
('Mamão Verde Em Tiras', 17),
('Salsicha Italiana Grelhada', 10),
('Cheddar Ralado 200g', 5),
('Fio de Ovo 24 Unidades', 8),
('Farinha de Trigo Integral', 11),
('Açúcar Refinado 2kg', 9),
('Pão Francesinha Crispado', 17),
('Arroz Vermelho Parboiled', 17),
('Bacon Cured', 11),
('Noz Vermelha Congelada', 18),
('Tomilho Fresco Curly', 11),
('Fubá Branco Moqueado', 17),
('Chouriço Caloroso Light', 13),
('Margarina Vegetal', 5),
('Salmão Empanado Congelado', 18),
('Couve Flor Ralado Fresh', 20),
('Salsicha Chouriçada em Tiras', 8),
('Linguinha de Porco Refogada', 20),
('Detergente Neutro Bio', 2),
('Couve Flor Ralado Shredded Broccoli', 20),
('Chouriço Frito', 5),
('Frijoles Negros 1kg', 15),
('Oliveira Picada', 8),
('Couve Tronchuda Fresh', 17),
('Molho de Cogumelos', 20),
('Fiosco Verde', 4),
('Açúcar Irmãos', 9),
('Feijão Preto Tipo 1', 8),
('Pó de Lavar Roupa', 4),
('Alho Crispado', 10),
('Feijão Branco Tipo 2', 8),
('Papel Higiênico Extra Soft', 8),
('Farofa Compostada', 10),
('Açúcar Granulada Brown Sugar', 9),
('Mandioca Branca 2,5kg', 4),
('Açúcar Granulado 500g', 9),
('Papel Toalha Duplo', 4),
('Flocos de Ouro 500g', 4),
('Pão Francês Integral', 7),
('Chouriço Italiano Spicy', 1),
('Café Solúvel Instantâneo', 10),
('Leitinho Condensado 150ml', 7),
('Frijoles Negros Culinados', 15),
('Cebola Vermelha Crispas', 20),
('Linguiça Caseira', 10),
('Arroz Vermelho Instantâneo', 17),
('Cebola Amarela Secca', 1),
('Açúcar Granulada 500g', 9),
('Aipo Ralado Secco', 17),
('Roupa de Cama Branca 1 Roll', 4),
('Salsicha Italiana', 1),
('Açaí Amazônico Congelado', 18),
('Hortelã Fresh', 2),
('Arroz Doce Instantâneo', 17),
('Tomilho Seco', 17),
('Algodão Extrafino', 18),
('Peixe Gordo Conservado', 17),
('Chouriço Mordomada', 8),
('Chouriço Caloroso', 9),
('Salgaro em Pó', 8),
('Tapioca Amarela 500g', 18),
('Flocos de Arroz Instantâneos', 4),
('Mandioca Amarela 2,5kg', 4),
('Pimenta Verde Grande', 4),
('Detergente Desinfetante', 6),
('Coxo de Galinha Mole Grelhado', 2),
('Pimenta Longa Extra Grande', 4),
('Cebolla Rija Polpa', 10),
('Tapioca Flour', 13),
('Fraldinha com Gengibre', 20),
('Torta de Canela', 17),
('Fubá Amarelo Moqueado', 17),
('Batata Doce', 10),
('Cebola Crispiante Fried Onion Ring', 20),
('Chouriço de Porco com Sabor', 17),
('Farofa Branca Integral', 11),
('Biscoito Integral', 11),
('Picanha de Porco Gourmet', 4),
('Leite Condensado 200ml', 7),
('Arroz Agulhinha Cozido', 9),
('Ovo Pastorizado', 8);

INSERT INTO public.products (name, group_id) VALUES 
('Arroz Integral 5kg', 11),
('Açucaragem de Cane', 13),
('Arroz Integral 10kg', 11),
('Fio de Ouro Fina', 17),
('Azeiteiro do Brasil', 11),
('Frutas Tropical Fresh 500g', 15),
('Torta de Figo Seco', 4),
('Tomate Hidropônico', 8),
('Mandioca Branca Fina', 4),
('Salsa Verde Picada', 9),
('Pimenta Calabresa Granel', 14),
('Ovo Largos', 8),
('Tortilha Whole Wheat', 11),
('Cebola Picada', 1),
('Tomate Cereja Conservado', 17),
('Tomate Saborido Fresco', 12),
('Peixe Conservado 150g', 17),
('Fiosco de Frango Desfiado', 3),
('Coxo de Cordeiro Grelhado', 17),
('Batata Doce 5kg', 4),
('Frango Grelado', 6),
('Levadura Instantânea', 10),
('Azeite com Açafrão', 20),
('Gergelim Sementeiro', 17),
('Noz Brancas', 10),
('Achocolatado', 9),
('Couve Flor Ralado', 17),
('Peixe Boi Conservado', 17),
('Tomate Cereja Jarred', 7),
('Papel Toalha Extra Strength', 11),
('Algodão Vermelho Fino', 4),
('Pimenta Verde', 4),
('Pimenta Preto Moledo', 8),
('Farofa Tostada com Salsa', 10),
('Geléia de Mirtilo', 8),
('Mussel Gordo Conservado', 17),
('Xarope de Açúcar', 9),
('Chá Earl Grey', 11),
('Cebola Crispas', 10),
('Laranja Escaldada', 19),
('Bacon Crocante', 10),
('Pimenta Calabrese Crispas', 14),
('Tapioca Gelée', 4);

